'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace CaptchaBlogComment


	Partial Public Class _Default

		''' <summary>
		''' Head1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' rptrComments control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected rptrComments As Global.System.Web.UI.WebControls.Repeater

		''' <summary>
		''' lblName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' tbName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' lblComment control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblComment As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' taComment control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected taComment As Global.System.Web.UI.HtmlControls.HtmlTextArea

		''' <summary>
		''' lblCaptcha control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblCaptcha As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' Captcha control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Captcha As Global.DevExpress.Web.ASPxEditors.ASPxCaptcha

		''' <summary>
		''' btnAddComment control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnAddComment As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' GuestBookDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GuestBookDataSource As Global.System.Web.UI.WebControls.XmlDataSource
	End Class
End Namespace
